#!/usr/bin/python3
import sys
import argparse

def main(args, lines):
  comp = open(args.wordlist).readlines()
  for line in lines:
     line = line.strip()
     for check in comp:
        check = check.strip()
        if check in line:
           print(line)
if __name__ == "__main__":
  parser = argparse.ArgumentParser()
  parser.add_argument('-w', '--wordlist', help="Wordlist to check against", required=True)
  args = parser.parse_args()
  lines = sys.stdin
  main(args, lines)
